### PR TITLE
fix Field.Bind usage

### LINKED ISSUE #55: Binding Custom Types by Specifying Binder Func Does Not Work
I think there may be something wrong with the example for custom types in README.md

```
func (t *MyType) FieldMap() binding.FieldMap {
	return binding.FieldMap{
		"number": binding.Field{
			Binder: func(fieldName string, formVals []string) error {
				val, err := strconv.Atoi(formVals[0])
				if err != nil {
					return binding.Errors{binding.NewError([]string{fieldName}, binding.DeserializationError, err.Error())}
				}
				t.SomeNumber = val
				return nil
			},
		},
	}
}
```

As written, my assumption is that binding will pick up the field's name from binding.FieldMap's key. However, I don't think this is happening.

Relevant extracts from binding.go set out for ease of reference:

binding.go:417
```
	for fieldPointer, fieldNameOrSpec := range fm {

		fieldSpec, err := fieldSpecification(fieldNameOrSpec)
		if err != nil {
			continue
		}

		strs := formData[fieldSpec.Form]
```

binding.go:758
```
func fieldSpecification(fieldNameOrSpec interface{}) (Field, error) {
	var f Field

	switch vt := fieldNameOrSpec.(type) {
	case Field:
		f = vt
	case string:
		f.Form = vt
	default:
		return f, errors.New("invalid field specification")
	}

	return f, nil
}
```

The list of strings passed to the Binder func is obtained from formData[fieldSpec.Form]. However in the example, fieldSpec.Form is not set and therefore strs will always be an empty array. This ends up with Binder func never being called as len(strs) == 0 (binding.go:429) is always true.

If I am correct, then there are two possible fixes:

1. If the intention is to pick up the field's name from binding.FieldMap's key, then fieldPointer should be passed to fieldSpecification and fieldSpecification should set fieldSpec.Form in the appropriate cases.
2. Otherwise, the example should be corrected to set fieldSpec.Form.

Hopefully I am not missing something obvious.

### PR DESCRIPTION
**Pull request by bhcleek**
Fix the usage of Field.Bind so that the field name is taken from the
field specification.

Correct README.md's example of using Field.Bind.

Add testable examples of Field.Bind and Binder and sync the testable
examples with the examples in README.md.

Fixes #55.

### CODE REVIEW

File: binding.go [hunk 1]
```diff
@@ -458,6 +454,10 @@ func bindForm(req *http.Request, userStruct FieldMapper, formData map[string][]s
 				}
 				continue
 			}
+
+			if len(strs) == 0 {
```
Comment (shihanng) [inline binding.go:458]: Hi @bhcleek, since `if len(strs) ...` is moved to bottom of this block, does this means that those who implements Binder interface need to check the length of the `strVals`?

```go
type MyBinder map[string]string

func (t MyBinder) Bind(fieldName string, strVals []string) error {
	if len(strVals) == 0 {
	    // do something here
	}
	t["formData"] = strVals[0]
	return nil
}
```
